"""add is_featured to menu items

Revision ID: ee890cb03af7
Revises: 45cd012bd7a3
Create Date: 2026-07-19 18:50:17.239779

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee890cb03af7"
down_revision: Union[str, None] = "45cd012bd7a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand: existing rows need a value for this new
    # NOT NULL column. New rows get their default from the app (Pydantic/
    # SQLAlchemy default=False), so this default isn't needed going forward,
    # but leaving it set is harmless and slightly more defensive.
    op.add_column(
        "menu_items",
        sa.Column("is_featured", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu_items", "is_featured")
    # ### end Alembic commands ###
